title: "Joshua Martin"
email: "joshuammar@gmail.com"
description: "Meet Josh Martin - SRE/DevOps Engineer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshuammar.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
quiet_deps: true
silence_deprecations: [import]

minima:
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/joshuammar/personal-website"
    - title: LinkedIn Profile
      icon: linkedin
      url: "https://www.linkedin.com/in/joshua-martin-28742765/"
  hide_site_feed_link: true
  
