title: "Joshua Martin"
email: "joshuammar@gmail.com"
description: “Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.” - Steve Jobs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshuammar.github.io" # the base hostname & protocol for your site
theme: minima
plugins: []

minima:
  skin: dark
  path: pages/
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/joshuammar/personal-website"
    - title: LinkedIn Profile
      icon: linkedin
      url: "https://www.linkedin.com/in/joshua-martin-28742765/"
  nav_pages:
    - pages/index.md
    - pages/projects.md
    - pages/resume.md
    - pages/hobbies.md
    - pages/contact.md
  hide_site_feed_link: true
  
