title: "Joshua Martin"
email: "joshuammar@gmail.com"
description: “Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.” - Steve Jobs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshuammar.github.io" # the base hostname & protocol for your site
theme: minima
plugins: []

minima:
  nav_pages:
    - pages/index.md
    - pages/projects.md
    - pages/resume.md
    - pages/hobbies.md
    - pages/contact.md